### ISSUE TITLE
Failing Enum deserialization

### ISSUE THREAD

**Issue by MartinKavik** [operutka/serde-lite#1]
Čau, 
I'm writing an example for [MoonZoon](https://github.com/MoonZoon/MoonZoon) and I've probably found a bug in enum deserialization. See errors in comments below.

```rust
// main.rs

use serde_lite::{Serialize, Deserialize};
use serde_json;

#[derive(Debug, Serialize, Deserialize)]
enum MyEnum {
    Variant1(Vec<u32>)
}

fn main() {
    let instance = MyEnum::Variant1(vec![
        // 123
    ]);

    // -- Serialization --
    
    let intermediate = instance.serialize().unwrap();
    let json = serde_json::to_string_pretty(&intermediate).unwrap();

    println!("JSON: {}", json);

    // -- Deserialization --

    let intermediate = serde_json::from_str(&json).unwrap();
    // vec![] => error MissingEnumVariantContent'
    // vec![123] => error UnnamedFieldErrors([(0, InvalidValue("array"))])'
    let instance = MyEnum::deserialize(&intermediate).unwrap();

    println!("INSTANCE: {:#?}", instance);
}
```
```toml
# Cargo.toml

[package]
name = "serde_lite_debug"
version = "0.1.0"
edition = "2018"

[dependencies]
# serde-lite = { version = "0.1.1", features = ["derive"] }
serde-lite = { git = "https://github.com/operutka/serde-lite", features = ["derive"] }
serde_json = "1.0.66"
```

Could you please look at it or direct me to a potential solution?
Thank you.
